// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqLOWQe20x0xVwy5aqwt9rMDjntjZlfsE',
    appId: '1:24828021726:web:5c071da894a3afc086eb4f',
    messagingSenderId: '24828021726',
    projectId: 'tdmu-book',
    authDomain: 'tdmu-book.firebaseapp.com',
    storageBucket: 'tdmu-book.appspot.com',
    measurementId: 'G-Z8QF3FDHZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ0fMLw-ff4FouZ209Tf3n79SOXhOpqNU',
    appId: '1:24828021726:android:b7bc8560eac644a486eb4f',
    messagingSenderId: '24828021726',
    projectId: 'tdmu-book',
    storageBucket: 'tdmu-book.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCspvUpqGenwatRPVicocQoLR1CwIbYFo',
    appId: '1:24828021726:ios:426d3ea38dd0481b86eb4f',
    messagingSenderId: '24828021726',
    projectId: 'tdmu-book',
    storageBucket: 'tdmu-book.appspot.com',
    iosBundleId: 'com.example.tdmubook',
  );
}
